package com.neu.nuboard.model;

import com.neu.nuboard.utils.UUIDutil;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "event") // psql table name
public class Event {
    /**
     * The UUID of the event.
     * id is a primary key of the event table.
     * It is generated by the database.
     */
    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private String id;

    /**
     * The title of the event.
     * title is a required field.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * The description of the event.
     * description is an optional field.
     */
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    /**
     * The start time of the event.
     * startTime is a required field.
     */
    @Column(name = "start_time", nullable = false)
    private LocalDateTime startTime;

    /**
     * The end time of the event.
     * endTime is a required field.
     */
    @Column(name = "end_time", nullable = false)
    private LocalDateTime endTime;

    /**
     * The location of the event.
     * location is a required field.
     */
    @Column(name = "location", nullable = false)
    private String location;

    /**
     * The type of organizer for the event (school or corporate).
     * organizerType is a required field.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "organizer_type", nullable = false)
    private OrganizerType organizerType;

    /**
     * The creator of the event.
     * creator is an object of type User.
     * one user can create many events.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "creator_id", nullable = false)
    private User creator;

    /**
     * The set of registrations for this event.
     * Each registration links a user to this event.
     */
    @OneToMany(mappedBy = "event", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<EventRegistration> registrations = new HashSet<>();

    /**
     * Default no-arg constructor required by JPA.
     */
    protected Event() {
        this.id = UUIDutil.getId();
    }

    /**
     * Constructor for a fully specified event.
     *
     * @param title The title of the event.
     * @param description The description of the event.
     * @param startTime The start time of the event.
     * @param endTime The end time of the event.
     * @param location The location of the event.
     * @param organizerType The type of organizer (school or corporate).
     * @param creator The creator of the event.
     */
    public Event(String title, String description, LocalDateTime startTime,
                 LocalDateTime endTime, String location, OrganizerType organizerType, User creator) {
        this.id = UUIDutil.getId();
        this.setTitle(title);
        this.description = description;
        this.setStartTime(startTime);
        this.setEndTime(endTime);
        this.setLocation(location);
        this.setOrganizerType(organizerType);
        this.setCreator(creator);
        this.registrations = new HashSet<>();
    }

    /**
     * Constructs a basic event with only required fields.
     *
     * @param title The title of the event.
     * @param eventDate The date of the event.
     * @param startTime The start time of the event.
     * @param endTime The end time of the event.
     * @param location The location of the event.
     * @param organizerType The type of organizer (school or corporate).
     * @param creator The creator of the event.
     */
    public Event(String title, LocalDateTime eventDate, LocalDateTime startTime, LocalDateTime endTime,
                 String location, OrganizerType organizerType, User creator) {
        this(title, "", startTime, endTime, location, organizerType, creator);
    }

    // Getters and Setters
    /**
     * Get the UUID of the event.
     * @return The UUID of the event.
     */
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    /**
     * Get the title of the event.
     * @return The title of the event.
     */
    public String getTitle() { return title; }
    public void setTitle(String title) {
        if (title == null || title.trim().isEmpty()) {
            throw new IllegalArgumentException("Title cannot be null or empty");
        }
        this.title = title;
    }

    /**
     * Get the description of the event.
     * @return The description of the event.
     */
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    /**
     * Get the start time of the event.
     * @return The start time of the event.
     */
    public LocalDateTime getStartTime() { return startTime; }
    public void setStartTime(LocalDateTime startTime) {
        if (startTime == null) {
            throw new IllegalArgumentException("Start time cannot be null.");
        }
        this.startTime = startTime;
    }

    /**
     * Get the end time of the event.
     * @return The end time of the event.
     */
    public LocalDateTime getEndTime() { return endTime; }
    public void setEndTime(LocalDateTime endTime) {
        if (endTime == null) {
            throw new IllegalArgumentException("End time cannot be null.");
        }
        this.endTime = endTime;
    }

    /**
     * Get the location of the event.
     * @return The location of the event.
     */
    public String getLocation() { return location; }
    public void setLocation(String location) {
        if (location == null || location.trim().isEmpty()) {
            throw new IllegalArgumentException("Location cannot be null or empty.");
        }
        this.location = location;
    }

    /**
     * Get the organizer type of the event.
     * @return The organizer type of the event.
     */
    public OrganizerType getOrganizerType() { return organizerType; }
    public void setOrganizerType(OrganizerType organizerType) {
        if (organizerType == null) {
            throw new IllegalArgumentException("Organizer type cannot be null.");
        }
        this.organizerType = organizerType;
    }

    /**
     * Get the creator of the event.
     * @return The creator of the event.
     */
    public User getCreator() { return creator; }
    public void setCreator(User creator) {
        if (creator == null) {
            throw new IllegalArgumentException("Creator cannot be null.");
        }
        this.creator = creator;
    }

    /**
     * Get the set of registrations for this event.
     * @return The set of registrations.
     */
    public Set<EventRegistration> getRegistrations() { return registrations; }
    public void setRegistrations(Set<EventRegistration> registrations) {
        this.registrations = (registrations != null) ? registrations : new HashSet<>();
    }

    /**
     * Validates that required fields are present and not empty.
     * @return True if the event is valid, false otherwise.
     */
    public boolean validate() {
        return title != null && !title.trim().isEmpty() &&
                startTime != null &&
                endTime != null &&
                location != null && !location.trim().isEmpty() &&
                organizerType != null &&
                creator != null;
    }

    /**
     * @return A string representation of the event.
     */
    @Override
    public String toString() {
        return "Event{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", location='" + location + '\'' +
                ", organizerType=" + organizerType +
                ", creator=" + creator +
                ", registrations=" + registrations +
                '}';
    }
}
