services:
  frontend:
    build: ./nuboard-front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nuboard-network

  backend:
    build: ./NUboard-services
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - nuboard-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: nuboard
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./NUboard-services/src/main/resources/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - nuboard-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nuboard"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

  broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kraft-kafka-broker
    ports:
      - "9094:9092"
    user: root
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9094
      KAFKA_LOG_DIRS: /tmp/kraft-kafka-logs
      CLUSTER_ID: "d3ICRQjoS3Kz70XfQU97wg"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kraft_broker_data:/tmp/kraft-kafka-logs
    networks:
      - nuboard-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
  kraft_broker_data:

networks:
  nuboard-network:
    driver: bridge
