spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nuboard

    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always     # ✅ 替代旧版 initialization-mode
      platform: postgres # ✅ 确保识别 PostgreSQL（可选）

  jpa:
    hibernate:
      ddl-auto: update # auto update db
    show-sql: true # sql log
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE